### ISSUE TITLE
Cannot change design from channel

### ISSUE THREAD

**Issue by mthpvg** [upfrontIO/livingdocs-manager#31]
See https://github.com/upfrontIO/livingdocs-design-timeline/pull/15 for the prerequisites in order to publish and upload a new design.

# Steps

## step 1
```bash
ldm design:publish dist/
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
info asset Succeeded to upload the file 'index.html'
info asset Succeeded to upload the file 'assets/images/html-embed.svg'
info asset Succeeded to upload the file 'assets/images/iframe-embed.svg'
info asset Succeeded to upload the file 'assets/images/applewatch.png'
info asset Succeeded to upload the file 'assets/images/tweet-embed.svg'
info asset Succeeded to upload the file 'stylesheets/timeline.css'
info asset Succeeded to upload the file 'assets/images/mountains.jpg'
info design:publish Published the design spaceline@0.3.1 to http://localhost:9090/designs/spaceline/0.3.1
```

## step 2
```bash
ldm channel:design-version:add --name spaceline --version 0.3.1 --channel 1
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
info channel:design-version:add The designVersion 0.3.1 is now linked to your channel.
```

## step 3
```bash
ldm channel:design-version:current --name spaceline --version 0.3.1 --channel 1
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
info channel:design-version:current The new current designVersion is 0.3.1.
```

## step 4
```bash
ldm project:channel:list
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
=== Default Channel Name
web

=== Channels
web
  channel id: 1
  design name: timeline
  current version: 0.3.1
  available versions: 0.4.3,0.3.1
  disabled versions
```

# Problem

From step 1 to 3 we use the design named spaceline (version is 0.3.1). But in step 4 the name remains timeline.

I've discussed with @marcbachmann about it. He says that you cannot change the design from a channel once it has been set but you can change the version number and this is what is happening here. It switches the version number of timeline and just ignore the the `name` parameter.

@masone

**Comment by mthpvg** [comment]
## Fail workaround

### Create a new channel
```bash
cd livingdocs-server
grunt channel-create
Requiring lib/events is deprecated, use liServer.events instead
Running "channel-create" task

Action: Create a channel
Select an environment:
? API environment local
Selected http://localhost:9090

Authenticate:
? Email mathieu@upfront.io
? Password ******
Logged in as mathieu pavageau

Enter the channel data:
? Channel name kepler
? Channel label tycho
? Design name spaceline
? Default design version 0.3.1
? Default Channel Mode default

Done, without errors.
```

### List channels
```bash
ldm project:channel:list
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
=== Default Channel Name
web

=== Channels
kepler
  channel id: 3
  design name: spaceline
  current version: 0.3.1
  available versions: 0.3.1
  disabled versions

web
  channel id: 1
  design name: timeline
  current version: 0.4.3
  available versions: 0.4.3
  disabled versions
```

### Publish new design
```bash
cd spaceline-timeline
ldm design:publish dist/
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
info asset Succeeded to upload the file 'assets/images/html-embed.svg'
info asset Succeeded to upload the file 'assets/images/tweet-embed.svg'
info asset Succeeded to upload the file 'index.html'
info asset Succeeded to upload the file 'assets/images/iframe-embed.svg'
info asset Succeeded to upload the file 'stylesheets/timeline.css'
info asset Succeeded to upload the file 'assets/images/mountains.jpg'
info asset Succeeded to upload the file 'assets/images/applewatch.png'
info design:publish Published the design spaceline@0.3.1 to http://localhost:9090/designs/spaceline/0.3.1
```

### Add design to channel
```bash
ldm channel:design-version:add --name spaceline --version 0.3.1 --channel 3
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
info channel:design-version:add The designVersion 0.3.1 is now linked to your channel.
```

### Set design as default
```bash
ldm channel:design-version:current --name spaceline --version 0.3.1 --channel 3
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
info channel:design-version:current The new current designVersion is 0.3.1.
```

## Problem

When trying to create a new article in the editor:
![selection_009](https://cloud.githubusercontent.com/assets/1951875/14111611/a28451e8-f5cb-11e5-9237-a9801f1636b8.png)

Can we remove the channel 1 or set channel 3 as default ?

I'll try to remove design from channel 1...

**Comment by mthpvg** [comment]
## Successful workaround

Create a new admin-user and choose from our local design repository the spaceline design that was uploaded earlier.
```bash
grunt setup-admin-user
Requiring lib/events is deprecated, use liServer.events instead
Running "setup-admin-user" task
? First name: mathieu
? Last name: pavageau
? Email: mth.pvg@gmail.com
? Password ******
? Project name: brahe
? Design name: spaceline
? Design version: 0.3.1
debug: Events: no subscriptions for the event 'project.create'
--------------------------------------
First name: mathieu
Last name: pavageau
Email: mth.pvg@gmail.com
Project name: brahe
Design: spaceline
Design Version: 0.3.1
--------------------------------------


Done, without errors.
```

**Comment by DaRaFF** [comment]
> From step 1 to 3 we use the design named spaceline (version is 0.3.1). But in step 4 the name remains timeline.
@marcbachmann's assumption was correct. If a channel has been created, it is not intended to change the design name. The name parameter gets ignored by ldm.

> Can we remove the channel 1 or set channel 3 as default ?

**Comment by DaRaFF** [comment]
> From step 1 to 3 we use the design named spaceline (version is 0.3.1). But in step 4 the name remains timeline.
@marcbachmann's assumption was correct. If a channel has been created, it is not intended to change the design name. The name parameter gets ignored by ldm.

> Can we remove the channel 1 or set channel 3 as default ?

* ldm doesn't support removing a channel or set a default channel
* deleting a channel can be done with a HTTP call to the server -> https://github.com/upfrontIO/livingdocs-server/blob/master/app/features/projects/routes/channel_routes.coffee#L13-L19
* setting the current design version (formerly know as default design) can be set via ldm -> ldm channel:design-version:current

**Comment by mthpvg** [comment]
Thanks for those answers :).

Regarding the last point: this is the current issue as described at the top of this discussion. At least it's not working for me.
I have tried again. I use a local repository that only contains the custom design named spaceline:

```bash
ldm project:channel:list
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
=== Default Channel Name
web

=== Channels
kepler
  channel id: 3
  design name: spaceline
  current version: 0.3.1
  available versions: 0.3.1
  disabled versions

web
  channel id: 1
  design name: timeline
  current version: 0.4.3
  available versions: 0.4.3
  disabled versions
```

```bash
ldm channel:design-version:current --name spaceline --version 0.3.1 --channel 1
? Host: http://localhost:9090
? Email: mathieu@upfront.io
? Password: ******
ERR! channel:design-version:current { [Error: Unhandled error:
ERR! channel:design-version:current     name: AppError
ERR! channel:design-version:current     message: The designVersion '0.3.1' can not set as current design version because it does not exist.
```
If I understand this right, this is because there is no timeline design version 0.3.1.

**Comment by DaRaFF** [comment]
Yes, the channel is a new layer between the project and the design. So in my view it wouldn't make sense to work exactly like before.

But during the implementation of the channel feature I noticed lack of consistency. Some functions can be called via ldm, some via grunt tasks at the ld-server and some endpoints are not supported at all by a tool. 

I guess it would make sense to create a GUI based admin tool to handle all functions which are not directly supported by the editor and are only used by an admin. //cc @peyerluk @marcbachmann

**Comment by masone** [comment]
Does it make sense to have an error message or something? It seems like the behavior was not clear at all to mathieu and he spent a lot of time figuring out what's going on. Even though the issue is closed, can we discuss how we could improve the workflow so this does not happen again?

**Comment by marcbachmann** [comment]
> Does it make sense to have an error message or something? It seems like the behavior was not clear at all to mathieu and he spent a lot of time figuring out what's going on. Even though the issue is closed, can we discuss how we could improve the workflow so this does not happen again?

Yes, like we're doing it in the server with the json, we have to make the command parsing more strict.
Also, don't waste the time. To complain that something isn't documented is better in this case.

**Comment by marcbachmann** [comment]
It's also time for some tests, even if we just pass the arguments to the rest api, where we have the logic.

**Comment by masone** [comment]
Cool! Who is in charge? Can you open an issue and describe it so we don't forget about it? :)
